name: view
description: 一款基于 Flutter 的图片分享社交 APP 的设计与实现

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:


  flutter:
    sdk: flutter
  provider: ^4.3.2+3
    # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.4.0+9
  
    # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5

  firebase_storage: ^3.1.6

  flutter_image_compress: ^0.7.0

  uuid: ^2.2.2

  path_provider: ^1.6.24

  cached_network_image: ^2.5.0

  image_picker: ^0.6.7+17

  animator: ^2.0.2

  intl: ^0.16.1

  image_cropper: ^1.3.1

  photofilters: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  image_path: "icon/logo.png" 
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/

  fonts:
    - family: PermanentMarker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
          weight: 700
